// <auto-generated />
namespace StepakJakub.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class commentsinposts : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(commentsinposts));
        
        string IMigrationMetadata.Id
        {
            get { return "201511111143082_comments-in-posts"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
